name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.3

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build-linux-amd64-HTTP
        run: bash build.sh HTTP

      - name: Build-linux-arm64-HTTP
        run: bash build.sh HTTP arm

      - name: Build-Win-amd64-HTTP
        run: bash build.sh HTTP win

      - name: Build-TencentSCF
        run: bash build.sh TencentSCF

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SMLKBOT
          path: |
            target/SMLKBOT
            target/SMLKBOT-arm64
            target/SMLKBOT-win.exe
            /target/SMLKBOTSCF
          
